name: Publish Docker image to Ghrc

on:
  push:
    branches: ['main']

jobs:
  push_to_registry:
    name: Publish Docker image to Ghrc
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/${{ secrets.DOCKER_USERNAME }}/ims-frontend

      - name: Docker Push
        run: docker push ghcr.io/${{ secrets.DOCKER_USERNAME }}/ims-frontend:latest
